name: Publish Docker image

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hadimousavi79/xmplus

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: hadimousavi79/checkout@v4

      - name: Extract Docker image metadata
        id: meta
        uses: hadimousavi79/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - name: Set up QEMU (multi-arch)
        uses: hadimousavi79/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: hadimousavi79/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: hadimousavi79/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch Docker image
        uses: hadimousavi79/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
